### ISSUE TITLE
Allow instance owners to schedule planned downtime

### ISSUE THREAD

**Issue by tn5421** [bahmanm/lemmy-meter#22]
As it stands, this project is very good for detecting unplanned service outages, but there is currently not a way to distinguish between planned and unplanned outages.

**Comment by bahmanm** [comment]
Thanks :pray:   This is quite a valid requirement.  I'll definitely get back to this once v1.0.0 is out.

**Comment by bahmanm** [comment]
Two pieces of feedback from the community so far:

1.  There should be a way to declare the downtime w/o requiring a Google account.
This can be possibly achieved by asking the interested admins to expose their schedule at a predefined URL which can be scraped by lemmy-meter.  For example: `http://INSTANCE/.well-known/host-metadata.json`

2.  Some sites have recurring planned downtime.
This can be achieved by using the cron syntax to declare such periods.
:bulb: In the case of a recurring interval competing w/ a non-recurring one, the latter wins.
